collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
typography_spectrum: 1
color:
  saturation: 0.2803399
  brandStrength: 0.3816849
  rhythmicContrast: 0.9178931
  brandColors:
    - '#67625E'
    - '#23262D'
    - '#FFFE88'
    - '#FF956B'
    - '#7E1C00'
  lightness: 0.4759419
layout_spectrum: 1
name: Paulthejohnson
